name: FullImage
author: michalc
category: Media
tags: [images, liquid, fluid, full screen, gallery]
docs: http://yetagain.net/plugins/fxpresets/docs/
demo: http://yetagain.net/plugins/fxpresets/demos/
